In [4]:
import numpy as np

In [6]:
x=np.array([[1],[2],[3]])

In [7]:
x.shape

(3, 1)

In [10]:
print(f"a 3D vector: \n{x}")

a 3D vector: 
[[1]
 [2]
 [3]]


In [14]:
y=np.array([[2],[3],[6]]);
sums=x+y
print(sums)

[[3]
 [5]
 [9]]


In [15]:
np.add(y,x)

array([[3],
       [5],
       [9]])

In [16]:
ar=[[1],[2],[3],[4]]
br=[[3],[4],[5],[7]]

In [18]:
x1=np.array(ar)
x2=np.array(br)

In [19]:
np.add(x1,x2)

array([[ 4],
       [ 6],
       [ 8],
       [11]])

In [23]:
alpha=2
x2*alpha

array([[ 6],
       [ 8],
       [10],
       [14]])

In [25]:
#multiply function
np.multiply(alpha,x2)

array([[ 6],
       [ 8],
       [10],
       [14]])

In [29]:
a,b=2,3
x, y=np.array([[2],[3]]),np.array([[4],[5]])
np.add(np.multiply(a,x),np.multiply(b,y))

array([[16],
       [21]])

In [30]:
x.T@y   #dot product 

array([[23]])

In [32]:
#euclidean norm (l2)
x = np.array([[3],[4]])
np.linalg.norm(x,2)

5.0

In [34]:
#manhattan norm (l1)
x = np.array([[3],[-4]])
np.linalg.norm(x,1)

7.0

In [37]:
#max norm or infinity norm 
x=np.array([[2],[4]])
np.linalg.norm(x, np.inf)

4.0

In [38]:
np.linalg.norm(x-y,2)

2.23606797749979

In [46]:
#angles()
cos_theta = (x.T@y)/ (np.linalg.norm(x,2) * (np.linalg.norm(y,2)))
print(cos_theta)
np.round(cos_theta,3)

[[0.97780241]]


array([[0.978]])

In [48]:
cos_inverse = np.arccos(cos_theta)
print(cos_inverse)

[[0.21109333]]


In [50]:
degree = cos_inverse *((180)/np.pi)
degree

array([[12.09475708]])

In [51]:
x, y = np.array([[2],[0]]), np.array([[0],[2]])

In [53]:
cos_theta = (x.T@y)/ (np.linalg.norm(x,2) * np.linalg.norm(y,2))
cos_theta

array([[0.]])

In [56]:
cos_inverse= np.arccos(cos_theta)
theta=cos_inverse * ((180)/np.pi)
theta

array([[90.]])